package com.joshisk.mathbingo;


public class LevelManager {
	private static ResourceManager RM = ResourceManager.getInstance();
	public static enum Level {
		EASY,
		MEDIUM,
		HARD
	}

	public void changeLevel(Level level) {
		RM.gameLevel = level;
		setLevelParameters();
	}
	
	public void setLevelParameters() {
		switch (RM.gameDataManager.getmLevel()) {
		/*case KIDS:
			RM.DEFAULT_MINIMUM_RESULT_NUMBER = 2;
			RM.DEFAULT_MAXIMUM_RESULT_NUMBER = 8;
			RM.DEFAULT_MINIMUM_GRID_NUMBER = 1;
			RM.DEFAULT_MAXIMUM_GRID_NUMBER = 30;

			RM.DEFAULT_DIVIDE_PERCENT = 5;
			RM.DEFAULT_MULTIPLY_PERCENT = 15;
			RM.DEFAULT_PLUS_PERCENT = 55;
			RM.DEFAULT_MINUS_PERCENT = 25;

			RM.DEFAULT_MAXIMUM_GREENS_ALLOWED = 5;
			break;*/
		case EASY:
			RM.DEFAULT_MINIMUM_RESULT_NUMBER = 5;
			RM.DEFAULT_MAXIMUM_RESULT_NUMBER = 30;
			RM.DEFAULT_MINIMUM_GRID_NUMBER = 1;
			RM.DEFAULT_MAXIMUM_GRID_NUMBER = 60;

			RM.DEFAULT_DIVIDE_PERCENT = 10;
			RM.DEFAULT_MULTIPLY_PERCENT = 15;
			RM.DEFAULT_PLUS_PERCENT = 40;
			RM.DEFAULT_MINUS_PERCENT = 35;

			RM.DEFAULT_MAXIMUM_GREENS_ALLOWED = 3;
			break;
		case MEDIUM:
			RM.DEFAULT_MINIMUM_RESULT_NUMBER = 15;
			RM.DEFAULT_MAXIMUM_RESULT_NUMBER = 40;
			RM.DEFAULT_MINIMUM_GRID_NUMBER = 1;
			RM.DEFAULT_MAXIMUM_GRID_NUMBER = 100;

			RM.DEFAULT_DIVIDE_PERCENT = 15;
			RM.DEFAULT_MULTIPLY_PERCENT = 20;
			RM.DEFAULT_PLUS_PERCENT = 25;
			RM.DEFAULT_MINUS_PERCENT = 40;

			RM.DEFAULT_MAXIMUM_GREENS_ALLOWED = 4;
			break;
		case HARD:
			RM.DEFAULT_MINIMUM_RESULT_NUMBER = 15;
			RM.DEFAULT_MAXIMUM_RESULT_NUMBER = 50;
			RM.DEFAULT_MINIMUM_GRID_NUMBER = 1;
			RM.DEFAULT_MAXIMUM_GRID_NUMBER = 127;

			RM.DEFAULT_DIVIDE_PERCENT = 25;
			RM.DEFAULT_MULTIPLY_PERCENT = 15;
			RM.DEFAULT_PLUS_PERCENT = 20;
			RM.DEFAULT_MINUS_PERCENT = 40;

			RM.DEFAULT_MAXIMUM_GREENS_ALLOWED = 6;
			break;

		default:
			break;
		}
	}
}
